@SmartMeetingRoom1_HostAddress = http://localhost:5128

GET {{SmartMeetingRoom1_HostAddress}}/weatherforecast/
Accept: application/json

### ?? Get a meeting by ID
GET {{host}}/api/meetings/1
Accept: application/json

### ? Create a new meeting
POST {{host}}/api/meetings
Content-Type: application/json

{
  "title": "AI Research Sync",
  "description": "Weekly sync meeting for research team",
  "startTime": "2025-08-04T09:00:00",
  "endTime": "2025-08-04T10:00:00",
  "roomId": 1,
  "organizerId": 1
}
